# genfont.ps1 - render simplified-Chinese glyphs with a real Windows font
# and emit kernel/cnfont_glyphs.h (16x16, row-major, top bit = leftmost).
# Regenerate after changing the CODEPOINTS list:  tools\genfont.ps1
# NOTE: ASCII-only source; characters come from codepoints below.
$ErrorActionPreference = 'Stop'
Set-Location (Split-Path $PSScriptRoot -Parent)
Add-Type -AssemblyName System.Drawing

# guo qing jie kuai le zu guo sheng ri (all simplified)
$codepoints = @(0x56FD, 0x5E86, 0x8282, 0x5FEB, 0x4E50, 0x7956, 0x751F, 0x65E5)
$fontname = 'SimSun'           # simplified Songti, ships with all Windows
$size = 16

# GDI+ family names are unreliable here (SimSun hidden, only -ExtB shows),
# so load font FILES directly via PrivateFontCollection.
$pfc = New-Object System.Drawing.Text.PrivateFontCollection
$cands = @('C:\Windows\Fonts\msyh.ttf','C:\Windows\Fonts\simhei.ttf',
           'C:\Windows\Fonts\simsun.ttc','C:\Windows\Fonts\simkai.ttf')
$fontfile = $null
foreach ($c in $cands) { if ([IO.File]::Exists($c)) { $fontfile = $c; break } }
if (-not $fontfile) { Write-Host "no CJK font file found" -ForegroundColor Red; exit 1 }
$pfc.AddFontFile($fontfile)
$fontname = $pfc.Families[0].Name
Write-Host "using font file: $fontfile ($fontname)"
Write-Host "using font: $fontname"

$chars = -join ($codepoints | ForEach-Object { [char]$_ })
$font = New-Object System.Drawing.Font($fontname, $size, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)
$out = New-Object Text.StringBuilder
[void]$out.AppendLine("/* AUTO-GENERATED by tools/genfont.ps1 - $fontname ${size}px, DO NOT EDIT BY HAND */")
[void]$out.AppendLine("#ifndef CNFONT_GLYPHS_H")
[void]$out.AppendLine("#define CNFONT_GLYPHS_H")
[void]$out.AppendLine('#include "stdint.h"')
[void]$out.AppendLine("")
[void]$out.AppendLine("static const glyph_t bank[] = {")

$bmp = New-Object System.Drawing.Bitmap($size, $size)
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAliasGridFit
$sf = New-Object System.Drawing.StringFormat
$sf.Alignment = [System.Drawing.StringAlignment]::Center
$sf.LineAlignment = [System.Drawing.StringAlignment]::Center

foreach ($ch in $chars.ToCharArray()) {
    $code = [int]$ch
    $g.Clear([System.Drawing.Color]::Black)
    $rect = New-Object System.Drawing.RectangleF(0, -1, $size, ($size + 2))
    $g.DrawString([string]$ch, $font, [System.Drawing.Brushes]::White, $rect, $sf)

    [void]$out.AppendLine(("    /* U+{0:X4} */" -f $code))
    [void]$out.AppendLine(("    {{ 0x{0:X4}, {{" -f $code))
    for ($y = 0; $y -lt $size; $y++) {
        $hi = 0; $lo = 0
        for ($x = 0; $x -lt 8; $x++) {
            if ($bmp.GetPixel($x, $y).R -gt 100) { $hi = $hi -bor (0x80 -shr $x) }
        }
        for ($x = 8; $x -lt 16; $x++) {
            if ($bmp.GetPixel($x, $y).R -gt 100) { $lo = $lo -bor (0x80 -shr ($x - 8)) }
        }
        $comma = if ($y -eq $size - 1) { "" } else { "," }
        [void]$out.AppendLine(("      0x{0:X2},0x{1:X2}{2}" -f $hi, $lo, $comma))
    }
    [void]$out.AppendLine("    }},")
}
$g.Dispose(); $bmp.Dispose()

# quick visual preview: the same chars at 4x size, saved for eyeballing
$pw = 4 * $size * $chars.Length; $ph = 4 * $size
$pv = New-Object System.Drawing.Bitmap($pw, $ph)
$pg = [System.Drawing.Graphics]::FromImage($pv)
$pg.Clear([System.Drawing.Color]::Black)
$big = New-Object System.Drawing.Font($fontname, (4 * $size), [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)
for ($i = 0; $i -lt $chars.Length; $i++) {
    $pg.DrawString([string]$chars[$i], $big, [System.Drawing.Brushes]::White,
                   (New-Object System.Drawing.RectangleF(($i * 4 * $size), 0, (4 * $size), (4 * $size))))
}
$pg.Dispose()
$pv.Save("build\glyph_preview.png", [System.Drawing.Imaging.ImageFormat]::Png)
$pv.Dispose()

[void]$out.AppendLine("};")
[void]$out.AppendLine("")
[void]$out.AppendLine("#endif /* CNFONT_GLYPHS_H */")
[IO.File]::WriteAllText("kernel\cnfont_glyphs.h", $out.ToString(), [Text.UTF8Encoding]::new($false))
Write-Host "wrote kernel\cnfont_glyphs.h ($($chars.Length) glyphs)"
